server:
  port: 8080

spring:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG

kotlin:
  coroutine:
    call-adapter:
      enabled: true

init-data: true
